# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Team

# Model Form Field configuration
form: $/masterpis/profile/models/team/fields.yaml

# Model Class name
modelClass: Masterpis\Profile\Models\Team

# Default redirect location
defaultRedirect: masterpis/profile/teams

# Create page
create:
    title: Create Team
    redirect: masterpis/profile/teams/update/:id
    redirectClose: masterpis/profile/teams

# Update page
update:
    title: Edit Team
    redirect: masterpis/profile/teams
    redirectClose: masterpis/profile/teams

# Preview page
preview:
    title: Preview Team
